ci:
  autofix_prs: false

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # ruff config is in ruff.toml
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: lint:format
        language: node
        language_version: system
        name: npm run lint:format
        entry: npm run lint:format
        types: [css, scss, javascript, ts, tsx, json, yaml]
      - id: lint:css
        language: node
        language_version: system
        name: npm run lint:css
        entry: npm run lint:css
        types: [css, scss]
