# Generated by Django 4.2.7 on 2023-12-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("prompt", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("replace", "Replace content"),
                            ("append", "Append after content"),
                        ],
                        default="replace",
                        help_text="The method to use when processing the prompt.",
                        max_length=25,
                    ),
                ),
            ],
        ),
    ]
