# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# for a detailed guide
name: Publish to PyPI

on:
  release:
    types: [published]

permissions: {}

jobs:
  test:
    uses: ./.github/workflows/test.yml
    permissions: {}
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'

      - name: Install Node dependencies
        run: npm ci

      - name: Build static files
        run: ./node_modules/.bin/webpack --mode production

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Build
        run: uv build

      # Smoke tests with ready-to-publish package.
      - name: Smoke test wheel
        run: |
          uv venv /tmp/smoketest-whl
          uv pip install --python /tmp/smoketest-whl dist/*.whl
          /tmp/smoketest-whl/bin/python -c "import wagtail_ai; print(wagtail_ai.__version__)"
      - name: Smoke test sdist
        run: |
          uv venv /tmp/smoketest-sdist
          uv pip install --python /tmp/smoketest-sdist dist/*.tar.gz
          /tmp/smoketest-sdist/bin/python -c "import wagtail_ai; print(wagtail_ai.__version__)"

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
      id-token: write # required for trusted publishing
    environment: publish
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: ./dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
