# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# for a detailed guide
name: Publish to PyPI

on:
  release:
    types: [published]

permissions: {}

jobs:
  test:
    uses: ./.github/workflows/test.yml
    permissions: {}
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: '.node-version'

      - name: Install Node dependencies
        run: npm ci

      - name: Build static files
        run: ./node_modules/.bin/webpack --mode production

      - name: Set up uv
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3.2.4

      - name: Build
        run: uv build

      # Smoke tests with ready-to-publish package.
      - name: Smoke test wheel
        run: |
          uv venv /tmp/smoketest-whl
          uv pip install --python /tmp/smoketest-whl dist/*.whl
          /tmp/smoketest-whl/bin/python -c "import wagtail_ai; print(wagtail_ai.__version__)"
      - name: Smoke test sdist
        run: |
          uv venv /tmp/smoketest-sdist
          uv pip install --python /tmp/smoketest-sdist dist/*.tar.gz
          /tmp/smoketest-sdist/bin/python -c "import wagtail_ai; print(wagtail_ai.__version__)"

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: ./dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
      id-token: write # required for trusted publishing
    environment: publish
    steps:
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: ./dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
